package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class utf8_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n<HTML>\r\n<HEAD>\r\n<TITLE>\r\nindex\r\n</TITLE>\r\n</HEAD>\r\n<BODY>\r\n<H1>\r\nUTF-8 Test Page\r\n</H1>\r\n\r\n<p>All the data on the page was sent to your browser in the UTF-8 encoding.</p>\r\n\r\n<p>Your browser identifies itself as: <b>");
      out.print( request.getHeader( "User-Agent" ) );
      out.write("</b>. </p>\r\n\r\n<p>Test of UTF-8 encoding of the Unicode characters 160-255 (the ISO-8859-1 set, AKA Latin-1)</p>\r\n<table border=\"1\" cellspacing=\"0\" cellpadding=\"3\">\r\n<tr><td>u00a0</td><td>");
      out.print( "\u00a0" );
      out.write("</td><td>NO-BREAK SPACE</td></tr>\r\n<tr><td>u00a1</td><td>");
      out.print( "\u00a1" );
      out.write("</td><td>INVERTED EXCLAMATION MARK</td></tr>\r\n<tr><td>u00a2</td><td>");
      out.print( "\u00a2" );
      out.write("</td><td>CENT SIGN</td></tr>\r\n<tr><td>u00a3</td><td>");
      out.print( "\u00a3" );
      out.write("</td><td>POUND SIGN</td></tr>\r\n<tr><td>u00a4</td><td>");
      out.print( "\u00a4" );
      out.write("</td><td>CURRENCY SIGN</td></tr>\r\n<tr><td>u00a5</td><td>");
      out.print( "\u00a5" );
      out.write("</td><td>YEN SIGN</td></tr>\r\n<tr><td>u00a6</td><td>");
      out.print( "\u00a6" );
      out.write("</td><td>BROKEN BAR</td></tr>\r\n<tr><td>u00a7</td><td>");
      out.print( "\u00a7" );
      out.write("</td><td>SECTION SIGN</td></tr>\r\n<tr><td>u00a8</td><td>");
      out.print( "\u00a8" );
      out.write("</td><td>DIAERESIS</td></tr>\r\n<tr><td>u00a9</td><td>");
      out.print( "\u00a9" );
      out.write("</td><td>COPYRIGHT SIGN</td></tr>\r\n<tr><td>u00aa</td><td>");
      out.print( "\u00aa" );
      out.write("</td><td>FEMININE ORDINAL INDICATOR</td></tr>\r\n<tr><td>u00ab</td><td>");
      out.print( "\u00ab" );
      out.write("</td><td>LEFT-POINTING DOUBLE ANGLE QUOTATION MARK</td></tr>\r\n<tr><td>u00ac</td><td>");
      out.print( "\u00ac" );
      out.write("</td><td>NOT SIGN</td></tr>\r\n<tr><td>u00ad</td><td>");
      out.print( "\u00ad" );
      out.write("</td><td>SOFT HYPHEN</td></tr>\r\n<tr><td>u00ae</td><td>");
      out.print( "\u00ae" );
      out.write("</td><td>REGISTERED SIGN</td></tr>\r\n<tr><td>u00af</td><td>");
      out.print( "\u00af" );
      out.write("</td><td>MACRON</td></tr>\r\n<tr><td>u00b0</td><td>");
      out.print( "\u00b0" );
      out.write("</td><td>DEGREE SIGN</td></tr>\r\n<tr><td>u00b1</td><td>");
      out.print( "\u00b1" );
      out.write("</td><td>PLUS-MINUS SIGN</td></tr>\r\n<tr><td>u00b2</td><td>");
      out.print( "\u00b2" );
      out.write("</td><td>SUPERSCRIPT TWO</td></tr>\r\n<tr><td>u00b3</td><td>");
      out.print( "\u00b3" );
      out.write("</td><td>SUPERSCRIPT THREE</td></tr>\r\n<tr><td>u00b4</td><td>");
      out.print( "\u00b4" );
      out.write("</td><td>ACUTE ACCENT</td></tr>\r\n<tr><td>u00b5</td><td>");
      out.print( "\u00b5" );
      out.write("</td><td>MICRO SIGN</td></tr>\r\n<tr><td>u00b6</td><td>");
      out.print( "\u00b6" );
      out.write("</td><td>PILCROW SIGN</td></tr>\r\n<tr><td>u00b7</td><td>");
      out.print( "\u00b7" );
      out.write("</td><td>MIDDLE DOT</td></tr>\r\n<tr><td>u00b8</td><td>");
      out.print( "\u00b8" );
      out.write("</td><td>CEDILLA</td></tr>\r\n<tr><td>u00b9</td><td>");
      out.print( "\u00b9" );
      out.write("</td><td>SUPERSCRIPT ONE</td></tr>\r\n<tr><td>u00ba</td><td>");
      out.print( "\u00ba" );
      out.write("</td><td>MASCULINE ORDINAL INDICATOR</td></tr>\r\n<tr><td>u00bb</td><td>");
      out.print( "\u00bb" );
      out.write("</td><td>RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK</td></tr>\r\n<tr><td>u00bc</td><td>");
      out.print( "\u00bc" );
      out.write("</td><td>VULGAR FRACTION ONE QUARTER</td></tr>\r\n<tr><td>u00bd</td><td>");
      out.print( "\u00bd" );
      out.write("</td><td>VULGAR FRACTION ONE HALF</td></tr>\r\n<tr><td>u00be</td><td>");
      out.print( "\u00be" );
      out.write("</td><td>VULGAR FRACTION THREE QUARTERS</td></tr>\r\n<tr><td>u00bf</td><td>");
      out.print( "\u00bf" );
      out.write("</td><td>INVERTED QUESTION MARK</td></tr>\r\n<tr><td>u00c0</td><td>");
      out.print( "\u00c0" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH GRAVE</td></tr>\r\n<tr><td>u00c1</td><td>");
      out.print( "\u00c1" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH ACUTE</td></tr>\r\n<tr><td>u00c2</td><td>");
      out.print( "\u00c2" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00c3</td><td>");
      out.print( "\u00c3" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH TILDE</td></tr>\r\n<tr><td>u00c4</td><td>");
      out.print( "\u00c4" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH DIAERESIS</td></tr>\r\n<tr><td>u00c5</td><td>");
      out.print( "\u00c5" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH RING ABOVE</td></tr>\r\n<tr><td>u00c6</td><td>");
      out.print( "\u00c6" );
      out.write("</td><td>LATIN CAPITAL LETTER AE</td></tr>\r\n<tr><td>u00c7</td><td>");
      out.print( "\u00c7" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH CEDILLA</td></tr>\r\n<tr><td>u00c8</td><td>");
      out.print( "\u00c8" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH GRAVE</td></tr>\r\n<tr><td>u00c9</td><td>");
      out.print( "\u00c9" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH ACUTE</td></tr>\r\n<tr><td>u00ca</td><td>");
      out.print( "\u00ca" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00cb</td><td>");
      out.print( "\u00cb" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH DIAERESIS</td></tr>\r\n<tr><td>u00cc</td><td>");
      out.print( "\u00cc" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH GRAVE</td></tr>\r\n<tr><td>u00cd</td><td>");
      out.print( "\u00cd" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH ACUTE</td></tr>\r\n<tr><td>u00ce</td><td>");
      out.print( "\u00ce" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00cf</td><td>");
      out.print( "\u00cf" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH DIAERESIS</td></tr>\r\n<tr><td>u00d0</td><td>");
      out.print( "\u00d0" );
      out.write("</td><td>LATIN CAPITAL LETTER ETH</td></tr>\r\n<tr><td>u00d1</td><td>");
      out.print( "\u00d1" );
      out.write("</td><td>LATIN CAPITAL LETTER N WITH TILDE</td></tr>\r\n<tr><td>u00d2</td><td>");
      out.print( "\u00d2" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH GRAVE</td></tr>\r\n<tr><td>u00d3</td><td>");
      out.print( "\u00d3" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH ACUTE</td></tr>\r\n<tr><td>u00d4</td><td>");
      out.print( "\u00d4" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00d5</td><td>");
      out.print( "\u00d5" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH TILDE</td></tr>\r\n<tr><td>u00d6</td><td>");
      out.print( "\u00d6" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH DIAERESIS</td></tr>\r\n<tr><td>u00d7</td><td>");
      out.print( "\u00d7" );
      out.write("</td><td>MULTIPLICATION SIGN</td></tr>\r\n<tr><td>u00d8</td><td>");
      out.print( "\u00d8" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH STROKE</td></tr>\r\n<tr><td>u00d9</td><td>");
      out.print( "\u00d9" );
      out.write("</td><td>LATIN CAPITAL LETTER U WITH GRAVE</td></tr>\r\n<tr><td>u00da</td><td>");
      out.print( "\u00da" );
      out.write("</td><td>LATIN CAPITAL LETTER U WITH ACUTE</td></tr>\r\n<tr><td>u00db</td><td>");
      out.print( "\u00db" );
      out.write("</td><td>LATIN CAPITAL LETTER U WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00dc</td><td>");
      out.print( "\u00dc" );
      out.write("</td><td>LATIN CAPITAL LETTER U WITH DIAERESIS</td></tr>\r\n<tr><td>u00dd</td><td>");
      out.print( "\u00dd" );
      out.write("</td><td>LATIN CAPITAL LETTER Y WITH ACUTE</td></tr>\r\n<tr><td>u00de</td><td>");
      out.print( "\u00de" );
      out.write("</td><td>LATIN CAPITAL LETTER THORN</td></tr>\r\n<tr><td>u00df</td><td>");
      out.print( "\u00df" );
      out.write("</td><td>LATIN SMALL LETTER SHARP S</td></tr>\r\n<tr><td>u00e0</td><td>");
      out.print( "\u00e0" );
      out.write("</td><td>LATIN SMALL LETTER A WITH GRAVE</td></tr>\r\n<tr><td>u00e1</td><td>");
      out.print( "\u00e1" );
      out.write("</td><td>LATIN SMALL LETTER A WITH ACUTE</td></tr>\r\n<tr><td>u00e2</td><td>");
      out.print( "\u00e2" );
      out.write("</td><td>LATIN SMALL LETTER A WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00e3</td><td>");
      out.print( "\u00e3" );
      out.write("</td><td>LATIN SMALL LETTER A WITH TILDE</td></tr>\r\n<tr><td>u00e4</td><td>");
      out.print( "\u00e4" );
      out.write("</td><td>LATIN SMALL LETTER A WITH DIAERESIS</td></tr>\r\n<tr><td>u00e5</td><td>");
      out.print( "\u00e5" );
      out.write("</td><td>LATIN SMALL LETTER A WITH RING ABOVE</td></tr>\r\n<tr><td>u00e6</td><td>");
      out.print( "\u00e6" );
      out.write("</td><td>LATIN SMALL LETTER AE</td></tr>\r\n<tr><td>u00e7</td><td>");
      out.print( "\u00e7" );
      out.write("</td><td>LATIN SMALL LETTER C WITH CEDILLA</td></tr>\r\n<tr><td>u00e8</td><td>");
      out.print( "\u00e8" );
      out.write("</td><td>LATIN SMALL LETTER E WITH GRAVE</td></tr>\r\n<tr><td>u00e9</td><td>");
      out.print( "\u00e9" );
      out.write("</td><td>LATIN SMALL LETTER E WITH ACUTE</td></tr>\r\n<tr><td>u00ea</td><td>");
      out.print( "\u00ea" );
      out.write("</td><td>LATIN SMALL LETTER E WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00eb</td><td>");
      out.print( "\u00eb" );
      out.write("</td><td>LATIN SMALL LETTER E WITH DIAERESIS</td></tr>\r\n<tr><td>u00ec</td><td>");
      out.print( "\u00ec" );
      out.write("</td><td>LATIN SMALL LETTER I WITH GRAVE</td></tr>\r\n<tr><td>u00ed</td><td>");
      out.print( "\u00ed" );
      out.write("</td><td>LATIN SMALL LETTER I WITH ACUTE</td></tr>\r\n<tr><td>u00ee</td><td>");
      out.print( "\u00ee" );
      out.write("</td><td>LATIN SMALL LETTER I WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00ef</td><td>");
      out.print( "\u00ef" );
      out.write("</td><td>LATIN SMALL LETTER I WITH DIAERESIS</td></tr>\r\n<tr><td>u00f0</td><td>");
      out.print( "\u00f0" );
      out.write("</td><td>LATIN SMALL LETTER ETH</td></tr>\r\n<tr><td>u00f1</td><td>");
      out.print( "\u00f1" );
      out.write("</td><td>LATIN SMALL LETTER N WITH TILDE</td></tr>\r\n<tr><td>u00f2</td><td>");
      out.print( "\u00f2" );
      out.write("</td><td>LATIN SMALL LETTER O WITH GRAVE</td></tr>\r\n<tr><td>u00f3</td><td>");
      out.print( "\u00f3" );
      out.write("</td><td>LATIN SMALL LETTER O WITH ACUTE</td></tr>\r\n<tr><td>u00f4</td><td>");
      out.print( "\u00f4" );
      out.write("</td><td>LATIN SMALL LETTER O WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00f5</td><td>");
      out.print( "\u00f5" );
      out.write("</td><td>LATIN SMALL LETTER O WITH TILDE</td></tr>\r\n<tr><td>u00f6</td><td>");
      out.print( "\u00f6" );
      out.write("</td><td>LATIN SMALL LETTER O WITH DIAERESIS</td></tr>\r\n<tr><td>u00f7</td><td>");
      out.print( "\u00f7" );
      out.write("</td><td>DIVISION SIGN</td></tr>\r\n<tr><td>u00f8</td><td>");
      out.print( "\u00f8" );
      out.write("</td><td>LATIN SMALL LETTER O WITH STROKE</td></tr>\r\n<tr><td>u00f9</td><td>");
      out.print( "\u00f9" );
      out.write("</td><td>LATIN SMALL LETTER U WITH GRAVE</td></tr>\r\n<tr><td>u00fa</td><td>");
      out.print( "\u00fa" );
      out.write("</td><td>LATIN SMALL LETTER U WITH ACUTE</td></tr>\r\n<tr><td>u00fb</td><td>");
      out.print( "\u00fb" );
      out.write("</td><td>LATIN SMALL LETTER U WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u00fc</td><td>");
      out.print( "\u00fc" );
      out.write("</td><td>LATIN SMALL LETTER U WITH DIAERESIS</td></tr>\r\n<tr><td>u00fd</td><td>");
      out.print( "\u00fd" );
      out.write("</td><td>LATIN SMALL LETTER Y WITH ACUTE</td></tr>\r\n<tr><td>u00fe</td><td>");
      out.print( "\u00fe" );
      out.write("</td><td>LATIN SMALL LETTER THORN</td></tr>\r\n<tr><td>u00ff</td><td>");
      out.print( "\u00ff" );
      out.write("</td><td>LATIN SMALL LETTER Y WITH DIAERESIS</td></tr>\r\n</table>\r\n\r\n<p>Test of UTF-8 encoding of the Unicode characters 256-383 (the Latin Extended-A set)</p>\r\n<table border=\"1\" cellspacing=\"0\" cellpadding=\"3\">\r\n<tr><td>u0100</td><td>");
      out.print( "\u0100" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH MACRON</td></tr>\r\n<tr><td>u0101</td><td>");
      out.print( "\u0101" );
      out.write("</td><td>LATIN SMALL LETTER A WITH MACRON</td></tr>\r\n<tr><td>u0102</td><td>");
      out.print( "\u0102" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH BREVE</td></tr>\r\n<tr><td>u0103</td><td>");
      out.print( "\u0103" );
      out.write("</td><td>LATIN SMALL LETTER A WITH BREVE</td></tr>\r\n<tr><td>u0104</td><td>");
      out.print( "\u0104" );
      out.write("</td><td>LATIN CAPITAL LETTER A WITH OGONEK</td></tr>\r\n<tr><td>u0105</td><td>");
      out.print( "\u0105" );
      out.write("</td><td>LATIN SMALL LETTER A WITH OGONEK</td></tr>\r\n<tr><td>u0106</td><td>");
      out.print( "\u0106" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH ACUTE</td></tr>\r\n<tr><td>u0107</td><td>");
      out.print( "\u0107" );
      out.write("</td><td>LATIN SMALL LETTER C WITH ACUTE</td></tr>\r\n<tr><td>u0108</td><td>");
      out.print( "\u0108" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u0109</td><td>");
      out.print( "\u0109" );
      out.write("</td><td>LATIN SMALL LETTER C WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u010a</td><td>");
      out.print( "\u010a" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH DOT ABOVE</td></tr>\r\n<tr><td>u010b</td><td>");
      out.print( "\u010b" );
      out.write("</td><td>LATIN SMALL LETTER C WITH DOT ABOVE</td></tr>\r\n<tr><td>u010c</td><td>");
      out.print( "\u010c" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH CARON</td></tr>\r\n<tr><td>u010d</td><td>");
      out.print( "\u010d" );
      out.write("</td><td>LATIN SMALL LETTER C WITH CARON</td></tr>\r\n<tr><td>u010e</td><td>");
      out.print( "\u010e" );
      out.write("</td><td>LATIN CAPITAL LETTER D WITH CARON</td></tr>\r\n<tr><td>u010f</td><td>");
      out.print( "\u010f" );
      out.write("</td><td>LATIN SMALL LETTER D WITH CARON</td></tr>\r\n<tr><td>u0110</td><td>");
      out.print( "\u0110" );
      out.write("</td><td>LATIN CAPITAL LETTER D WITH STROKE</td></tr>\r\n<tr><td>u0111</td><td>");
      out.print( "\u0111" );
      out.write("</td><td>LATIN SMALL LETTER D WITH STROKE</td></tr>\r\n<tr><td>u0112</td><td>");
      out.print( "\u0112" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH MACRON</td></tr>\r\n<tr><td>u0113</td><td>");
      out.print( "\u0113" );
      out.write("</td><td>LATIN SMALL LETTER E WITH MACRON</td></tr>\r\n<tr><td>u0114</td><td>");
      out.print( "\u0114" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH BREVE</td></tr>\r\n<tr><td>u0115</td><td>");
      out.print( "\u0115" );
      out.write("</td><td>LATIN SMALL LETTER E WITH BREVE</td></tr>\r\n<tr><td>u0116</td><td>");
      out.print( "\u0116" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH DOT ABOVE</td></tr>\r\n<tr><td>u0117</td><td>");
      out.print( "\u0117" );
      out.write("</td><td>LATIN SMALL LETTER E WITH DOT ABOVE</td></tr>\r\n<tr><td>u0118</td><td>");
      out.print( "\u0118" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH OGONEK</td></tr>\r\n<tr><td>u0119</td><td>");
      out.print( "\u0119" );
      out.write("</td><td>LATIN SMALL LETTER E WITH OGONEK</td></tr>\r\n<tr><td>u011a</td><td>");
      out.print( "\u011a" );
      out.write("</td><td>LATIN CAPITAL LETTER E WITH CARON</td></tr>\r\n<tr><td>u011b</td><td>");
      out.print( "\u011b" );
      out.write("</td><td>LATIN SMALL LETTER E WITH CARON</td></tr>\r\n<tr><td>u011c</td><td>");
      out.print( "\u011c" );
      out.write("</td><td>LATIN CAPITAL LETTER G WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u011d</td><td>");
      out.print( "\u011d" );
      out.write("</td><td>LATIN SMALL LETTER G WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u011e</td><td>");
      out.print( "\u011e" );
      out.write("</td><td>LATIN CAPITAL LETTER G WITH BREVE</td></tr>\r\n<tr><td>u011f</td><td>");
      out.print( "\u011f" );
      out.write("</td><td>LATIN SMALL LETTER G WITH BREVE</td></tr>\r\n<tr><td>u0120</td><td>");
      out.print( "\u0120" );
      out.write("</td><td>LATIN CAPITAL LETTER G WITH DOT ABOVE</td></tr>\r\n<tr><td>u0121</td><td>");
      out.print( "\u0121" );
      out.write("</td><td>LATIN SMALL LETTER G WITH DOT ABOVE</td></tr>\r\n<tr><td>u0122</td><td>");
      out.print( "\u0122" );
      out.write("</td><td>LATIN CAPITAL LETTER G WITH CEDILLA</td></tr>\r\n<tr><td>u0123</td><td>");
      out.print( "\u0123" );
      out.write("</td><td>LATIN SMALL LETTER G WITH CEDILLA</td></tr>\r\n<tr><td>u0124</td><td>");
      out.print( "\u0124" );
      out.write("</td><td>LATIN CAPITAL LETTER H WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u0125</td><td>");
      out.print( "\u0125" );
      out.write("</td><td>LATIN SMALL LETTER H WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u0126</td><td>");
      out.print( "\u0126" );
      out.write("</td><td>LATIN CAPITAL LETTER H WITH STROKE</td></tr>\r\n<tr><td>u0127</td><td>");
      out.print( "\u0127" );
      out.write("</td><td>LATIN SMALL LETTER H WITH STROKE</td></tr>\r\n<tr><td>u0128</td><td>");
      out.print( "\u0128" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH TILDE</td></tr>\r\n<tr><td>u0129</td><td>");
      out.print( "\u0129" );
      out.write("</td><td>LATIN SMALL LETTER I WITH TILDE</td></tr>\r\n<tr><td>u012a</td><td>");
      out.print( "\u012a" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH MACRON</td></tr>\r\n<tr><td>u012b</td><td>");
      out.print( "\u012b" );
      out.write("</td><td>LATIN SMALL LETTER I WITH MACRON</td></tr>\r\n<tr><td>u012c</td><td>");
      out.print( "\u012c" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH BREVE</td></tr>\r\n<tr><td>u012d</td><td>");
      out.print( "\u012d" );
      out.write("</td><td>LATIN SMALL LETTER I WITH BREVE</td></tr>\r\n<tr><td>u012e</td><td>");
      out.print( "\u012e" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH OGONEK</td></tr>\r\n<tr><td>u012f</td><td>");
      out.print( "\u012f" );
      out.write("</td><td>LATIN SMALL LETTER I WITH OGONEK</td></tr>\r\n<tr><td>u0130</td><td>");
      out.print( "\u0130" );
      out.write("</td><td>LATIN CAPITAL LETTER I WITH DOT ABOVE</td></tr>\r\n<tr><td>u0131</td><td>");
      out.print( "\u0131" );
      out.write("</td><td>LATIN SMALL LETTER DOTLESS I</td></tr>\r\n<tr><td>u0132</td><td>");
      out.print( "\u0132" );
      out.write("</td><td>LATIN CAPITAL LIGATURE IJ</td></tr>\r\n<tr><td>u0133</td><td>");
      out.print( "\u0133" );
      out.write("</td><td>LATIN SMALL LIGATURE IJ</td></tr>\r\n<tr><td>u0134</td><td>");
      out.print( "\u0134" );
      out.write("</td><td>LATIN CAPITAL LETTER J WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u0135</td><td>");
      out.print( "\u0135" );
      out.write("</td><td>LATIN SMALL LETTER J WITH CIRCUMFLEX</td></tr>\r\n<tr><td>u0136</td><td>");
      out.print( "\u0136" );
      out.write("</td><td>LATIN CAPITAL LETTER K WITH CEDILLA</td></tr>\r\n<tr><td>u0137</td><td>");
      out.print( "\u0137" );
      out.write("</td><td>LATIN SMALL LETTER K WITH CEDILLA</td></tr>\r\n<tr><td>u0138</td><td>");
      out.print( "\u0138" );
      out.write("</td><td>LATIN SMALL LETTER KRA</td></tr>\r\n<tr><td>u0139</td><td>");
      out.print( "\u0139" );
      out.write("</td><td>LATIN CAPITAL LETTER L WITH ACUTE</td></tr>\r\n<tr><td>u013a</td><td>");
      out.print( "\u013a" );
      out.write("</td><td>LATIN SMALL LETTER L WITH ACUTE</td></tr>\r\n<tr><td>u013b</td><td>");
      out.print( "\u013b" );
      out.write("</td><td>LATIN CAPITAL LETTER L WITH CEDILLA</td></tr>\r\n<tr><td>u013c</td><td>");
      out.print( "\u013c" );
      out.write("</td><td>LATIN SMALL LETTER L WITH CEDILLA</td></tr>\r\n<tr><td>u013d</td><td>");
      out.print( "\u013d" );
      out.write("</td><td>LATIN CAPITAL LETTER L WITH CARON</td></tr>\r\n<tr><td>u013e</td><td>");
      out.print( "\u013e" );
      out.write("</td><td>LATIN SMALL LETTER L WITH CARON</td></tr>\r\n<tr><td>u013f</td><td>");
      out.print( "\u013f" );
      out.write("</td><td>LATIN CAPITAL LETTER L WITH MIDDLE DOT</td></tr>\r\n<tr><td>u0140</td><td>");
      out.print( "\u0140" );
      out.write("</td><td>LATIN SMALL LETTER L WITH MIDDLE DOT</td></tr>\r\n<tr><td>u0141</td><td>");
      out.print( "\u0141" );
      out.write("</td><td>LATIN CAPITAL LETTER L WITH STROKE</td></tr>\r\n<tr><td>u0142</td><td>");
      out.print( "\u0142" );
      out.write("</td><td>LATIN SMALL LETTER L WITH STROKE</td></tr>\r\n<tr><td>u0143</td><td>");
      out.print( "\u0143" );
      out.write("</td><td>LATIN CAPITAL LETTER N WITH ACUTE</td></tr>\r\n<tr><td>u0144</td><td>");
      out.print( "\u0144" );
      out.write("</td><td>LATIN SMALL LETTER N WITH ACUTE</td></tr>\r\n<tr><td>u0145</td><td>");
      out.print( "\u0145" );
      out.write("</td><td>LATIN CAPITAL LETTER N WITH CEDILLA</td></tr>\r\n<tr><td>u0146</td><td>");
      out.print( "\u0146" );
      out.write("</td><td>LATIN SMALL LETTER N WITH CEDILLA</td></tr>\r\n<tr><td>u0147</td><td>");
      out.print( "\u0147" );
      out.write("</td><td>LATIN CAPITAL LETTER N WITH CARON</td></tr>\r\n<tr><td>u0148</td><td>");
      out.print( "\u0148" );
      out.write("</td><td>LATIN SMALL LETTER N WITH CARON</td></tr>\r\n<tr><td>u0149</td><td>");
      out.print( "\u0149" );
      out.write("</td><td>LATIN SMALL LETTER N PRECEDED BY APOSTROPHE</td></tr>\r\n<tr><td>u014a</td><td>");
      out.print( "\u014a" );
      out.write("</td><td>LATIN CAPITAL LETTER ENG</td></tr>\r\n<tr><td>u014b</td><td>");
      out.print( "\u014b" );
      out.write("</td><td>LATIN SMALL LETTER ENG</td></tr>\r\n<tr><td>u014c</td><td>");
      out.print( "\u014c" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH MACRON</td></tr>\r\n<tr><td>u014d</td><td>");
      out.print( "\u014d" );
      out.write("</td><td>LATIN SMALL LETTER O WITH MACRON</td></tr>\r\n<tr><td>u014e</td><td>");
      out.print( "\u014e" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH BREVE</td></tr>\r\n<tr><td>u014f</td><td>");
      out.print( "\u014f" );
      out.write("</td><td>LATIN SMALL LETTER O WITH BREVE</td></tr>\r\n<tr><td>u0150</td><td>");
      out.print( "\u0150" );
      out.write("</td><td>LATIN CAPITAL LETTER O WITH DOUBLE ACUTE</td></tr>\r\n<tr><td>u0151</td><td>");
      out.print( "\u0151" );
      out.write("</td><td>LATIN SMALL LETTER O WITH DOUBLE ACUTE</td></tr>\r\n<tr><td>u0152</td><td>");
      out.print( "\u0152" );
      out.write("</td><td>LATIN CAPITAL LIGATURE OE</td></tr>\r\n<tr><td>u0153</td><td>");
      out.print( "\u0153" );
      out.write("</td><td>LATIN SMALL LIGATURE OE</td></tr>\r\n<tr><td>u0154</td><td>");
      out.print( "\u0154" );
      out.write("</td><td>LATIN CAPITAL LETTER R WITH ACUTE</td></tr>\r\n<tr><td>u0155</td><td>");
      out.print( "\u0155" );
      out.write("</td><td>LATIN SMALL LETTER R WITH ACUTE</td></tr>\r\n<tr><td>u0156</td><td>");
      out.print( "\u0156" );
      out.write("</td><td>LATIN CAPITAL LETTER R WITH CEDILLA</td></tr>\r\n<tr><td>u0157</td><td>");
      out.print( "\u0157" );
      out.write("</td><td>LATIN SMALL LETTER R WITH CEDILLA</td></tr>\r\n<tr><td>u0158</td><td>");
      out.print( "\u0158" );
      out.write("</td><td>LATIN CAPITAL LETTER R WITH CARON</td></tr>\r\n<tr><td>u0159</td><td>");
      out.print( "\u0159" );
      out.write("</td><td>LATIN SMALL LETTER R WITH CARON</td></tr>\r\n<tr><td>u015a</td><td>");
      out.print( "\u015a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u015b</td><td>");
      out.print( "\u015b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u015c</td><td>");
      out.print( "\u015c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u015d</td><td>");
      out.print( "\u015d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u015e</td><td>");
      out.print( "\u015e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u015f</td><td>");
      out.print( "\u015f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0160</td><td>");
      out.print( "\u0160" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0161</td><td>");
      out.print( "\u0161" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0162</td><td>");
      out.print( "\u0162" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0163</td><td>");
      out.print( "\u0163" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0164</td><td>");
      out.print( "\u0164" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0165</td><td>");
      out.print( "\u0165" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0166</td><td>");
      out.print( "\u0166" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0167</td><td>");
      out.print( "\u0167" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0168</td><td>");
      out.print( "\u0168" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0169</td><td>");
      out.print( "\u0169" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016a</td><td>");
      out.print( "\u016a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016b</td><td>");
      out.print( "\u016b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016c</td><td>");
      out.print( "\u016c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016d</td><td>");
      out.print( "\u016d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016e</td><td>");
      out.print( "\u016e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u016f</td><td>");
      out.print( "\u016f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0170</td><td>");
      out.print( "\u0170" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0171</td><td>");
      out.print( "\u0171" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0172</td><td>");
      out.print( "\u0172" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0173</td><td>");
      out.print( "\u0173" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0174</td><td>");
      out.print( "\u0174" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0175</td><td>");
      out.print( "\u0175" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0176</td><td>");
      out.print( "\u0176" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0177</td><td>");
      out.print( "\u0177" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0178</td><td>");
      out.print( "\u0178" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0179</td><td>");
      out.print( "\u0179" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017a</td><td>");
      out.print( "\u017a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017b</td><td>");
      out.print( "\u017b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017c</td><td>");
      out.print( "\u017c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017d</td><td>");
      out.print( "\u017d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017e</td><td>");
      out.print( "\u017e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u017f</td><td>");
      out.print( "\u017f" );
      out.write("</td><td></td></tr>\r\n</table>\r\n\r\n<p>Test of UTF-8 encoding of the Unicode characters 0180-024F (the Latin Extended-B set)</p>\r\n<table border=\"1\" cellspacing=\"0\" cellpadding=\"3\">\r\n<tr><td>u0180</td><td>");
      out.print( "\u0180" );
      out.write("</td><td>LATIN SMALL LETTER B WITH STROKE</td></tr>\r\n<tr><td>u0181</td><td>");
      out.print( "\u0181" );
      out.write("</td><td>LATIN CAPITAL LETTER B WITH HOOK</td></tr>\r\n<tr><td>u0182</td><td>");
      out.print( "\u0182" );
      out.write("</td><td>LATIN CAPITAL LETTER B WITH TOPBAR</td></tr>\r\n<tr><td>u0183</td><td>");
      out.print( "\u0183" );
      out.write("</td><td>LATIN SMALL LETTER B WITH TOPBAR</td></tr>\r\n<tr><td>u0184</td><td>");
      out.print( "\u0184" );
      out.write("</td><td>LATIN CAPITAL LETTER TONE SIX</td></tr>\r\n<tr><td>u0185</td><td>");
      out.print( "\u0185" );
      out.write("</td><td>LATIN SMALL LETTER TONE SIX</td></tr>\r\n<tr><td>u0186</td><td>");
      out.print( "\u0186" );
      out.write("</td><td>LATIN CAPITAL LETTER OPEN O</td></tr>\r\n<tr><td>u0187</td><td>");
      out.print( "\u0187" );
      out.write("</td><td>LATIN CAPITAL LETTER C WITH HOOK</td></tr>\r\n<tr><td>u0188</td><td>");
      out.print( "\u0188" );
      out.write("</td><td>LATIN SMALL LETTER C WITH HOOK</td></tr>\r\n<tr><td>u0189</td><td>");
      out.print( "\u0189" );
      out.write("</td><td>LATIN CAPITAL LETTER AFRICAN D</td></tr>\r\n<tr><td>u018a</td><td>");
      out.print( "\u018a" );
      out.write("</td><td>LATIN CAPITAL LETTER D WITH HOOK</td></tr>\r\n<tr><td>u018b</td><td>");
      out.print( "\u018b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u018c</td><td>");
      out.print( "\u018c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u018d</td><td>");
      out.print( "\u018d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u018e</td><td>");
      out.print( "\u018e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u018f</td><td>");
      out.print( "\u018f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0190</td><td>");
      out.print( "\u0190" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0191</td><td>");
      out.print( "\u0191" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0192</td><td>");
      out.print( "\u0192" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0193</td><td>");
      out.print( "\u0193" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0194</td><td>");
      out.print( "\u0194" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0195</td><td>");
      out.print( "\u0195" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0196</td><td>");
      out.print( "\u0196" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0197</td><td>");
      out.print( "\u0197" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0198</td><td>");
      out.print( "\u0198" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0199</td><td>");
      out.print( "\u0199" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019a</td><td>");
      out.print( "\u019a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019b</td><td>");
      out.print( "\u019b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019c</td><td>");
      out.print( "\u019c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019d</td><td>");
      out.print( "\u019d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019e</td><td>");
      out.print( "\u019e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u019f</td><td>");
      out.print( "\u019f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a0</td><td>");
      out.print( "\u01a0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a1</td><td>");
      out.print( "\u01a1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a2</td><td>");
      out.print( "\u01a2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a3</td><td>");
      out.print( "\u01a3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a4</td><td>");
      out.print( "\u01a4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a5</td><td>");
      out.print( "\u01a5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a6</td><td>");
      out.print( "\u01a6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a7</td><td>");
      out.print( "\u01a7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a8</td><td>");
      out.print( "\u01a8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01a9</td><td>");
      out.print( "\u01a9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01aa</td><td>");
      out.print( "\u01aa" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ab</td><td>");
      out.print( "\u01ab" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ac</td><td>");
      out.print( "\u01ac" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ad</td><td>");
      out.print( "\u01ad" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ae</td><td>");
      out.print( "\u01ae" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01af</td><td>");
      out.print( "\u01af" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b0</td><td>");
      out.print( "\u01b0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b1</td><td>");
      out.print( "\u01b1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b2</td><td>");
      out.print( "\u01b2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b3</td><td>");
      out.print( "\u01b3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b4</td><td>");
      out.print( "\u01b4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b5</td><td>");
      out.print( "\u01b5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b6</td><td>");
      out.print( "\u01b6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b7</td><td>");
      out.print( "\u01b7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b8</td><td>");
      out.print( "\u01b8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01b9</td><td>");
      out.print( "\u01b9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ba</td><td>");
      out.print( "\u01ba" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01bb</td><td>");
      out.print( "\u01bb" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01bc</td><td>");
      out.print( "\u01bc" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01bd</td><td>");
      out.print( "\u01bd" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01be</td><td>");
      out.print( "\u01be" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01bf</td><td>");
      out.print( "\u01bf" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c0</td><td>");
      out.print( "\u01c0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c1</td><td>");
      out.print( "\u01c1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c2</td><td>");
      out.print( "\u01c2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c3</td><td>");
      out.print( "\u01c3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c4</td><td>");
      out.print( "\u01c4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c5</td><td>");
      out.print( "\u01c5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c6</td><td>");
      out.print( "\u01c6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c7</td><td>");
      out.print( "\u01c7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c8</td><td>");
      out.print( "\u01c8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01c9</td><td>");
      out.print( "\u01c9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ca</td><td>");
      out.print( "\u01ca" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01cb</td><td>");
      out.print( "\u01cb" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01cc</td><td>");
      out.print( "\u01cc" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01cd</td><td>");
      out.print( "\u01cd" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ce</td><td>");
      out.print( "\u01ce" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01cf</td><td>");
      out.print( "\u01cf" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d0</td><td>");
      out.print( "\u01d0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d1</td><td>");
      out.print( "\u01d1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d2</td><td>");
      out.print( "\u01d2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d3</td><td>");
      out.print( "\u01d3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d4</td><td>");
      out.print( "\u01d4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d5</td><td>");
      out.print( "\u01d5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d6</td><td>");
      out.print( "\u01d6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d7</td><td>");
      out.print( "\u01d7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d8</td><td>");
      out.print( "\u01d8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01d9</td><td>");
      out.print( "\u01d9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01da</td><td>");
      out.print( "\u01da" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01db</td><td>");
      out.print( "\u01db" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01dc</td><td>");
      out.print( "\u01dc" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01dd</td><td>");
      out.print( "\u01dd" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01de</td><td>");
      out.print( "\u01de" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01df</td><td>");
      out.print( "\u01df" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e0</td><td>");
      out.print( "\u01e0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e1</td><td>");
      out.print( "\u01e1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e2</td><td>");
      out.print( "\u01e2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e3</td><td>");
      out.print( "\u01e3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e4</td><td>");
      out.print( "\u01e4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e5</td><td>");
      out.print( "\u01e5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e6</td><td>");
      out.print( "\u01e6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e7</td><td>");
      out.print( "\u01e7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e8</td><td>");
      out.print( "\u01e8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01e9</td><td>");
      out.print( "\u01e9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ea</td><td>");
      out.print( "\u01ea" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01eb</td><td>");
      out.print( "\u01eb" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ec</td><td>");
      out.print( "\u01ec" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ed</td><td>");
      out.print( "\u01ed" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ee</td><td>");
      out.print( "\u01ee" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ef</td><td>");
      out.print( "\u01ef" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f0</td><td>");
      out.print( "\u01f0" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f1</td><td>");
      out.print( "\u01f1" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f2</td><td>");
      out.print( "\u01f2" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f3</td><td>");
      out.print( "\u01f3" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f4</td><td>");
      out.print( "\u01f4" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f5</td><td>");
      out.print( "\u01f5" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f6</td><td>");
      out.print( "\u01f6" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f7</td><td>");
      out.print( "\u01f7" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f8</td><td>");
      out.print( "\u01f8" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01f9</td><td>");
      out.print( "\u01f9" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01fa</td><td>");
      out.print( "\u01fa" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01fb</td><td>");
      out.print( "\u01fb" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01fc</td><td>");
      out.print( "\u01fc" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01fd</td><td>");
      out.print( "\u01fd" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01fe</td><td>");
      out.print( "\u01fe" );
      out.write("</td><td></td></tr>\r\n<tr><td>u01ff</td><td>");
      out.print( "\u01ff" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0200</td><td>");
      out.print( "\u0200" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0201</td><td>");
      out.print( "\u0201" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0202</td><td>");
      out.print( "\u0202" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0203</td><td>");
      out.print( "\u0203" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0204</td><td>");
      out.print( "\u0204" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0205</td><td>");
      out.print( "\u0205" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0206</td><td>");
      out.print( "\u0206" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0207</td><td>");
      out.print( "\u0207" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0208</td><td>");
      out.print( "\u0208" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0209</td><td>");
      out.print( "\u0209" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020a</td><td>");
      out.print( "\u020a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020b</td><td>");
      out.print( "\u020b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020c</td><td>");
      out.print( "\u020c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020d</td><td>");
      out.print( "\u020d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020e</td><td>");
      out.print( "\u020e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u020f</td><td>");
      out.print( "\u020f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0210</td><td>");
      out.print( "\u0210" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0211</td><td>");
      out.print( "\u0211" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0212</td><td>");
      out.print( "\u0212" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0213</td><td>");
      out.print( "\u0213" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0214</td><td>");
      out.print( "\u0214" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0215</td><td>");
      out.print( "\u0215" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0216</td><td>");
      out.print( "\u0216" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0217</td><td>");
      out.print( "\u0217" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0218</td><td>");
      out.print( "\u0218" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0219</td><td>");
      out.print( "\u0219" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021a</td><td>");
      out.print( "\u021a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021b</td><td>");
      out.print( "\u021b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021c</td><td>");
      out.print( "\u021c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021d</td><td>");
      out.print( "\u021d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021e</td><td>");
      out.print( "\u021e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u021f</td><td>");
      out.print( "\u021f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0220</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0221</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0222</td><td>");
      out.print( "\u0222" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0223</td><td>");
      out.print( "\u0223" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0224</td><td>");
      out.print( "\u0224" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0225</td><td>");
      out.print( "\u0225" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0226</td><td>");
      out.print( "\u0226" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0227</td><td>");
      out.print( "\u0227" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0228</td><td>");
      out.print( "\u0228" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0229</td><td>");
      out.print( "\u0229" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022a</td><td>");
      out.print( "\u022a" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022b</td><td>");
      out.print( "\u022b" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022c</td><td>");
      out.print( "\u022c" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022d</td><td>");
      out.print( "\u022d" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022e</td><td>");
      out.print( "\u022e" );
      out.write("</td><td></td></tr>\r\n<tr><td>u022f</td><td>");
      out.print( "\u022f" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0230</td><td>");
      out.print( "\u0230" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0231</td><td>");
      out.print( "\u0231" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0232</td><td>");
      out.print( "\u0232" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0233</td><td>");
      out.print( "\u0233" );
      out.write("</td><td></td></tr>\r\n<tr><td>u0234</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0235</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0236</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0237</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0238</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0239</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023A</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023B</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023C</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023D</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023E</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u023F</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n");
      out.write("<tr><td>u0240</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0241</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0242</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0243</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0244</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0245</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0246</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0247</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0248</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u0249</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u024A</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u024B</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n");
      out.write("<tr><td>u024C</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u024D</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u024E</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n<tr><td>u024F</td><td>&nbsp;         </td><td>Unicode character not defined</td></tr>\r\n</table>\r\n\r\n</BODY>\r\n</HTML>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
